// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent() (Event, func(), error) {
	simpleMessage, cleanup, err := NewSimpleMessage()
	if err != nil {
		return Event{}, nil, err
	}
	greeter := NewGreeter(simpleMessage)
	event := NewEvent(greeter)
	return event, func() {
		cleanup()
	}, nil
}
